### ISSUE TITLE
No ways to enable TLS for OpenShift 4 routes

### ISSUE THREAD

**Issue by nebula0248** [3scale/apicast-operator#78]
**Problem**
Currently, there is a tls object parameter under APIcast.spec.exposedHost. This tls parameter will create an Ingress object with TLS configuration. However, when the operator is used in OpenShift 4, and since OpenShift 4 uses Route objects instead of Ingress, there are no ways for me to make a Route to be TLS-enabled, or implement TLS edge termination.

**Expected behavior**
Provide another parameter in the APICast operator spec definition specifically for OpenShift for TLS.

https://github.com/3scale/apicast-operator/blob/4fc739e7e9d9dbb24bf3bcffc087ae50ca6d5e44/deploy/crds/apps.3scale.net_apicasts_crd.yaml

**Comment by miguelsorianod** [comment]
Hi @nebula0248,

Thanks for opening the issue.

When an Ingress is created a Route object is automatically created. However, there are some unsupported scenarios by OpenShift 4.x at the moment when using TLS:
We have an issue where this same issue was reported. You can see details on the issue here: https://issues.redhat.com/browse/THREESCALE-5485. There you will find the issues associated to the OpenShift project with a discussion on it.

**Comment by nebula0248** [comment]
@miguelsorianod Thank you very much for your prompt comment. Yes, your link matches exactly what I am looking for. It is great to know that I can manually create another secure route as a workaround (which can solve my problem at this moment). Hope the problem can be officially solved one day :)
